# Project information
site_name: DocsRef
site_url: https://docsref.com
site_author: Austin
site_description: >-
  Information, fast

# Repository
repo_name: jzstraley/docsref
repo_url: https://github.com/jzstraley/docsref/

# Copyright
copyright: Copyright &copy; 2022 - 2024 Austin

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: docsref
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: IBM Plex Sans
    code: JetBrains Mono
  favicon: favicon.ico
  logo: D2.svg

# Plugins
plugins:
  - blog:
      blog_dir: resources/blog/
      post_date_format: short
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/stylesheets/extra.css
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: iso_datetime
      timezone: America/Detroit
      fallback_to_build_date: true

strict: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-WNN51ZP6S1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jzstraley
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/austinthefamilyguy/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jamesstraley
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Straley/

# Extra CSS
extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: IMTechEd
      repo: IMTechEd
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: 'index.md'
  - IM Guide:
    - im-guide/index.md
    - Cardiology:
      - ACS: im-guide/cards/acs.md
      - Cardiac Critical Care: 
        - Cardiogenic Shock: im-guide/cards/cardiac-critical-care/cardiogenic-shock.md
        - LV Failure: im-guide/cards/cardiac-critical-care/lv-failure.md
        - RV Failure: im-guide/cards/cardiac-critical-care/rv-failure.md
      - Congenital Heart Disease: im-guide/cards/congenital-heart-disease.md
      - Consults: im-guide/cards/consults.md
      - Echo: 
        - Aortic Valve: im-guide/cards/echo/aorticvalve.md
        - Echo Chapter 1: im-guide/cards/echo/chapter1.md
      - EKG: im-guide/cards/ekg.md
      - Electrophysiology: 
        - Atrial Fibrillation: im-guide/cards/electrophysiology/atrial-fibrillation.md
      - Heart Failure: 
        - im-guide/cards/heart-failure/index.md
        - Acute Heart Failure:
          - im-guide/cards/heart-failure/acute-hf/index.md
          - Acute Decompensated Heart Failure: im-guide/cards/heart-failure/acute-hf/acute-decompensated-hf.md
        - Chronic Heart Failure:
          - im-guide/cards/heart-failure/chronic-hf/index.md
          - Heart Failure with Preserved Ejection Fraction: im-guide/cards/heart-failure/chronic-hf/hfpef.md
          - Heart Failure with Reduced Ejection Fraction: im-guide/cards/heart-failure/chronic-hf/hfref.md
      - Imaging: im-guide/cards/imaging.md
      - Invasive Cardiology: im-guide/cards/invasive-cardiology.md
      - Nuclear Cardiology: im-guide/cards/nuclear-cardiology.md
      - Other Topics: 
        - Syncope: im-guide/cards/other-topics/syncope.md
        - Hypertension: im-guide/cards/other-topics/hypertension.md
      - Pericardial Disease: im-guide/cards/pericardial-disease.md
      - Pharmacology: 
        - Antianginals: im-guide/pharm/cardiac-pharm/antianginals.md
        - Antiarrhythmics: im-guide/pharm/cardiac-pharm/antiarrhythmics.md
        - Antihypertensives: im-guide/pharm/cardiac-pharm/antihypertensives.md
        - Lipid Therapy: im-guide/pharm/cardiac-pharm/lipidtherapy.md
      - Prevention:
        - Lipids: im-guide/cards/prevention/lipids.md
      - Stable Ischemic Disease: im-guide/cards/stable-ischemic-disease.md
      - Vascular Disease: 
        - im-guide/cards/vascular-disease/index.md
        - Hypertension: im-guide/cards/vascular-disease/hypertension.md
      - Valvular Heart Disease: 
        - im-guide/cards/valvular-heart-disease/index.md
    - Dermatology: 
      - im-guide/derm/index.md
    - Endocrinology: 
      - im-guide/endo/index.md
    - Gastroenterology: 
      - im-guide/gi/index.md
    - General: 
      - im-guide/general/index.md
      - Perioperative Management of Surgical Patients: im-guide/general/perioperative.md
    - Geriatrics: 
      - im-guide/geri/index.md
    - Hematology/Oncology: 
      - im-guide/heme-onc/index.md
    - Infectious Disease: 
      - im-guide/id/index.md
    - Neurology: 
      - CNS Disease:
        - Cortex: 
          - Dementia: 
            - im-guide/neuro/cns-disease/cortex/dementia/index.md
            - Cortical Dementia: im-guide/neuro/cns-disease/cortex/dementia/cortical.md
            - Mixed Dementia: im-guide/neuro/cns-disease/cortex/dementia/mixed.md
          - Altered Mental Status (AMS): im-guide/neuro/cns-disease/cortex/ams.md
          - Coma: im-guide/neuro/cns-disease/cortex/coma.md
          - Seizure Disorders: im-guide/neuro/cns-disease/cortex/seizures.md
        - Subcortex: 
          - im-guide/neuro/cns-disease/subcortex/index.md
        - Ventricles/CSF: 
          - Headaches: im-guide/neuro/cns-disease/ventricles-csf/headaches.md
        - Global:
          - Trauma: im-guide/neuro/cns-disease/global/trauma.md
        - Miscellaneous:
          - Vertigo:
            - im-guide/neuro/cns-disease/miscellaneous/vertigo/index.md
        - Neoplasms & Tumors: 
          - im-guide/neuro/cns-disease/neoplasms-tumors/index.md
        - Neurocutaneous Disease: 
          - im-guide/neuro/cns-disease/neurocutaneous/index.md
        - Treatment Modalities: 
          - im-guide/neuro/cns-disease/treatment-modalities/index.md
    - Nephrology: 
      - Renal Anatomy: im-guide/nephro/renal-anatomy.md
      - Renal Physiology: im-guide/nephro/renal-physiology.md
      - Urinalysis: im-guide/nephro/urinalysis.md
      - Electrolytes: 
        - im-guide/nephro/electrolytes/index.md
        - Hypernatremia: im-guide/nephro/electrolytes/hypernatremia.md
        - Hyponatremia: im-guide/nephro/electrolytes/hyponatremia.md
        - Hypomagnesemia: im-guide/nephro/electrolytes/hypomagnesemia.md
        - Hyperkalemia: im-guide/nephro/electrolytes/hyperkalemia.md
        - Hypokalemia: im-guide/nephro/electrolytes/hypokalemia.md
        - Hypercalcemia: im-guide/nephro/electrolytes/hypercalcemia.md
        - Hypocalcemia: im-guide/nephro/electrolytes/hypocalcemia.md
        - Hyperphosphatemia: im-guide/nephro/electrolytes/hyperphosphatemia.md
        - Hypophosphatemia: im-guide/nephro/electrolytes/hypophosphatemia.md
        - Hypermagnesemia: im-guide/nephro/electrolytes/hypermagnesemia.md
      - AKI: im-guide/nephro/aki.md
      - CKD: im-guide/nephro/ckd.md
    - Pharmacology:
      - Autonomics: im-guide/pharm/autonomics.md
      - Chemotherapy & ID:
        - Antibiotics: im-guide/pharm/chemo-id/antibiotics.md
        - Antiemetics: im-guide/pharm/chemo-id/antiemetics.md
        - Antivirals: im-guide/pharm/chemo-id/antivirals.md
        - Oncologic Meds: im-guide/pharm/chemo-id/oncologic_meds.md
      - Endocrine:
        - Anti-Obesity: im-guide/pharm/endocrine/antiobesity.md
        - Diabetes Management: im-guide/pharm/endocrine/diabetes_management.md
        - Osteoporosis: im-guide/pharm/endocrine/osteoporosis.md
        - Thyroid Meds: im-guide/pharm/endocrine/thyroid_meds.md
      - Labs and Side Effects:
        - General: im-guide/pharm/labs-and-se/general.md
        - Labs: im-guide/pharm/labs-and-se/labs.md
        - Other: im-guide/pharm/labs-and-se/other.md
        - Side Effects: im-guide/pharm/labs-and-se/side_effects.md
      - Nervous System:
        - Anesthetics: im-guide/pharm/nervous-system/anesthetics.md
        - Anticonvulsants: im-guide/pharm/nervous-system/anticonvulsants.md
        - CNS Drugs: im-guide/pharm/nervous-system/cnsdrugs.md
        - ICU: im-guide/pharm/nervous-system/icu.md
        - Pain Management: im-guide/pharm/nervous-system/pain_management.md
        - Sleep: im-guide/pharm/nervous-system/sleep.md
      - Psychiatry:
        - Antidepressants: im-guide/pharm/psychiatry/antidepressants.md
        - Antipsychotics: im-guide/pharm/psychiatry/antipsychotics.md
        - Anxiolytics: im-guide/pharm/psychiatry/anxiolytics.md
        - Mood Stabilizers: im-guide/pharm/psychiatry/mood_stabilizers.md
        - Stimulants: im-guide/pharm/psychiatry/stimulants.md
      - Smooth Muscle:
        - Anaphylaxis: im-guide/pharm/smooth-muscle/anaphylaxis.md
        - Antihistamines: im-guide/pharm/smooth-muscle/antihistamines.md
        - Antipruritics: im-guide/pharm/smooth-muscle/antipruritics.md
        - Asthma/COPD: im-guide/pharm/smooth-muscle/asthma-copd.md
        - Decongestants: im-guide/pharm/smooth-muscle/decongestants.md
      - Special Topics:
        - Antidiarrheals: im-guide/pharm/special-topics/antidiarrheals.md
        - Contraceptives: im-guide/pharm/special-topics/contraceptives.md
        - Dermatology: im-guide/pharm/special-topics/dermatology.md
        - GERD: im-guide/pharm/special-topics/gerd.md
        - Laxatives: im-guide/pharm/special-topics/laxatives.md
        - Pregnancy: im-guide/pharm/special-topics/pregnancy.md
        - Prostate: im-guide/pharm/special-topics/prostate.md
        - Vitamins: im-guide/pharm/special-topics/vitamins.md
      - Toxicology: im-guide/pharm/tox/index.md
      - Blood & Anti-inflammatories:
        - Antiplatelets: im-guide/pharm/blood&anti-inflammatories/antiplatelets.md
        - Antithrombotics: im-guide/pharm/blood&anti-inflammatories/antithrombotics.md
        - Fibrinolytics: im-guide/pharm/blood&anti-inflammatories/fibrinolytics.md
        - Gout: im-guide/pharm/blood&anti-inflammatories/gout.md
        - Steroids: im-guide/pharm/blood&anti-inflammatories/steroids.md
    - Psychiatry:
      - im-guide/psych/index.md
    - Pulmonology/Critical Care: 
      - im-guide/pccm/index.md
      - General: im-guide/pccm/general.md
      - FASTHUGSBID: im-guide/pccm/fasthugsbid.md
    - Rheumatology: 
      - im-guide/rheum/index.md
    - Student/Intern Readings: im-guide/student-intern-readings.md
  - Resident Guide:
    - Basics: resident-guide/1-basics.md
    - Team Expectations: resident-guide/2-team-expectations.md
    - Staying Organized: resident-guide/3-staying-organized.md
    - How to Write an Admission Note: resident-guide/4-how-to-write-admit-note.md
    - Transfers: resident-guide/5-transfers.md
    - Discharge: resident-guide/6-discharge.md
    - Patient Instructions: resident-guide/7-patient-instructions.md
    - Common Inpatient Problems: resident-guide/8-common-inpt-problems.md
    - Licensing: resident-guide/9-licensing.md
  - Resources:
    - Concepts: resources/concepts.md
    - Cerner: resources/cernerhelp.md
    - Dotphrases: resources/dotphrases.md
    - Important Websites: resources/important-websites.md
    - Shortcuts: resources/shortcuts.md
    - How to Search More Effectively Online: resources/how-to-search-more-effectively.md
    - Workload Management: resources/workload-management.md
    - Interesting: resources/interesting.md
    - Blog: 
      - resources/blog/index.md
  - Tags: tags.md
  - About: 
    - about/index.md
    - Disclaimer: about/disclaimer.md
    - License: about/license.md
    - Site Development: about/site-development.md
    - Changelog: about/changelog.md
    - Contact: about/contact.md

validation:
  links:
    absolute_links: ignore

watch:
  - material

exclude_docs:
  draft/