# Project information
site_name: Docsref
site_url: https://www.docsref.com/
site_author: Austin
site_description: >-
  Information, fast

# Repository
repo_name: jzstraley/docsref
repo_url: https://github.com/jzstraley/docsref/

# Copyright
copyright: Copyright &copy; 2022 - 2024 Austin

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo3-copy-invert.png

# Plugins
plugins:
  - blog:
      blog_dir: .
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/stylesheets/extra.css
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: iso_datetime
      timezone: America/Detroit
      fallback_to_build_date: true

strict: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-DRP25XGTN2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jzstraley
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/austinthefamilyguy/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jamesstraley
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Straley/

# Extra CSS
extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: IMTechEd
      repo: IMTechEd
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: 'index.md'
  - Guide:
    - guide/index.md
    - Student/Intern Readings: guide/student-intern-readings.md
    - Cardiology:
      - guide/cardiology/index.md
      - ACS: guide/cardiology/acs.md
      - Cardiac Critical Care: guide/cardiology/cardiac-critical-care.md
      - Congenital Heart Disease: guide/cardiology/congenital-heart-disease.md
      - Consults: guide/cardiology/consults.md
      - Echo: guide/cardiology/echo.md
      - EKG: guide/cardiology/ekg.md
      - Electrophysiology: 
        - guide/cardiology/electrophysiology/index.md
        - Atrial Fibrillation: guide/cardiology/electrophysiology/atrial-fibrillation.md
      - Heart Failure: guide/cardiology/heart-failure.md
      - Imaging: guide/cardiology/imaging.md
      - Invasive Cardiology: guide/cardiology/invasive-cardiology.md
      - Nuclear Cardiology: guide/cardiology/nuclear-cardiology.md
      - Other Topics: 
        - guide/cardiology/other-topics/index.md
        - Syncope: guide/cardiology/other-topics/syncope.md
      - Pericardial Disease: guide/cardiology/pericardial-disease.md
      - Pharmacology: guide/cardiology/pharmacology-cardiology.md
      - Prevention: 
        - guide/cardiology/prevention/index.md
        - Lipids: guide/cardiology/prevention/lipids.md
      - Reasarch: guide/cardiology/research.md
      - Stable Ischemic Disease: guide/cardiology/stable-ischemic-disease.md
      - Vascular Disease: 
        - guide/cardiology/vascular-disease/index.md
        - Hypertension: guide/cardiology/vascular-disease/hypertension.md
      - Valvular Heart Disease: 
        - guide/cardiology/valvular-heart-disease/index.md
    - Dermatology: guide/dermatology.md
    - Endocrinology: guide/endocrinology.md
    - Gastroenterology: guide/gastroenterology.md
    - General: guide/general.md
    - Geriatrics: guide/geriatrics.md
    - Hematology/Oncology: guide/hematology-oncology.md
    - Infectious Disease: guide/infectious-disease.md
    - Neurology: guide/neurology.md
    - Nephrology: 
      - guide/nephrology/index.md
      - Renal Anatomy: guide/nephrology/renal-anatomy.md
      - Renal Physiology: guide/nephrology/renal-physiology.md
      - Electrolytes: 
        - guide/nephrology/electrolytes/index.md
        - Hypernatremia: guide/nephrology/electrolytes/hypernatremia.md
        - Hyponatremia: guide/nephrology/electrolytes/hyponatremia.md
        - Hypomagnesemia: guide/nephrology/electrolytes/hypomagnesemia.md
        - Hyperkalemia: guide/nephrology/electrolytes/hyperkalemia.md
        - Hypokalemia: guide/nephrology/electrolytes/hypokalemia.md
        - Hypercalcemia: guide/nephrology/electrolytes/hypercalcemia.md
        - Hypocalcemia: guide/nephrology/electrolytes/hypocalcemia.md
        - Hyperphosphatemia: guide/nephrology/electrolytes/hyperphosphatemia.md
        - Hypophosphatemia: guide/nephrology/electrolytes/hypophosphatemia.md
        - Hypermagnesemia: guide/nephrology/electrolytes/hypermagnesemia.md
      - AKI: guide/nephrology/aki.md
      - CKD: guide/nephrology/ckd.md
    - Pharmacology: 
      - guide/pharmacology/index.md
      - Autonomics: guide/pharmacology/autonomics.md
      - Chemotherapy & ID:
        - guide/pharmacology/Chemotherapy & ID/index.md
        - Antibiotics: guide/pharmacology/Chemotherapy & ID/antibiotics.md
        - Antiemetics: guide/pharmacology/Chemotherapy & ID/antiemetics.md
        - Antivirals: guide/pharmacology/Chemotherapy & ID/antivirals.md
        - Oncologic Meds: guide/pharmacology/Chemotherapy & ID/oncologic_meds.md
      - Endocrine:
        - guide/pharmacology/Endocrine/index.md
        - Anti-Obesity: guide/pharmacology/Endocrine/antiobesity.md
        - Diabetes Management: guide/pharmacology/Endocrine/diabetes_management.md
        - Osteoporosis: guide/pharmacology/Endocrine/osteoporosis.md
        - Thyroid Meds: guide/pharmacology/Endocrine/thyroid_meds.md
      - Labs and Side Effects:
        - guide/pharmacology/Labs and Side Effects/index.md
        - General: guide/pharmacology/Labs and Side Effects/general.md
        - Labs: guide/pharmacology/Labs and Side Effects/labs.md
        - Other: guide/pharmacology/Labs and Side Effects/other.md
        - Side Effects: guide/pharmacology/Labs and Side Effects/side_effects.md
      - Nervous System:
        - guide/pharmacology/Nervous System/index.md
        - Anesthetics: guide/pharmacology/Nervous System/anesthetics.md
        - Anticonvulsants: guide/pharmacology/Nervous System/anticonvulsants.md
        - CNS Drugs: guide/pharmacology/Nervous System/cnsdrugs.md
        - ICU: guide/pharmacology/Nervous System/icu.md
        - Pain Management: guide/pharmacology/Nervous System/pain_management.md
        - Sleep: guide/pharmacology/Nervous System/sleep.md
      - Psychiatry:
        - guide/pharmacology/Psychiatry/index.md
        - Antidepressants: guide/pharmacology/Psychiatry/antidepressants.md
        - Antipsychotics: guide/pharmacology/Psychiatry/antipsychotics.md
        - Anxiolytics: guide/pharmacology/Psychiatry/anxiolytics.md
        - Mood Stabilizers: guide/pharmacology/Psychiatry/mood_stabilizers.md
        - Stimulants: guide/pharmacology/Psychiatry/stimulants.md
      - Smooth Muscle:
        - guide/pharmacology/Smooth Muscle/index.md
        - Anaphylaxis: guide/pharmacology/Smooth Muscle/anaphylaxis.md
        - Antihistamines: guide/pharmacology/Smooth Muscle/antihistamines.md
        - Antipruritics: guide/pharmacology/Smooth Muscle/antipruritics.md
        - Asthma/COPD: guide/pharmacology/Smooth Muscle/asthma-copd.md
        - Decongestants: guide/pharmacology/Smooth Muscle/decongestants.md
      - Special Topics:
        - guide/pharmacology/Special Topics/index.md
        - Antidiarrheals: guide/pharmacology/Special Topics/antidiarrheals.md
        - Contraceptives: guide/pharmacology/Special Topics/contraceptives.md
        - Dermatology: guide/pharmacology/Special Topics/dermatology.md
        - GERD: guide/pharmacology/Special Topics/gerd.md
        - Laxatives: guide/pharmacology/Special Topics/laxatives.md
        - Pregnancy: guide/pharmacology/Special Topics/pregnancy.md
        - Prostate: guide/pharmacology/Special Topics/prostate.md
        - Vitamins: guide/pharmacology/Special Topics/vitamins.md
      - Toxicology: guide/pharmacology/Toxicology/index.md
      - Blood & Anti-inflammatories:
        - guide/pharmacology/blood&anti-inflammatories/index.md
        - Antiplatelets: guide/pharmacology/blood&anti-inflammatories/antiplatelets.md
        - Antithrombotics: guide/pharmacology/blood&anti-inflammatories/antithrombotics.md
        - Gout: guide/pharmacology/blood&anti-inflammatories/gout.md
        - Steroids: guide/pharmacology/blood&anti-inflammatories/steroids.md
      - Cardiovascular Renal:
        - guide/pharmacology/cardiovascular-renal/index.md
        - Antianginals: guide/pharmacology/cardiovascular-renal/antianginals.md
        - Antiarrhythmics: guide/pharmacology/cardiovascular-renal/antiarrhythmics.md
        - Antihypertensives: guide/pharmacology/cardiovascular-renal/antihypertensives.md
        - Lipid Therapy: guide/pharmacology/cardiovascular-renal/lipidtherapy.md
    - Pulmonology/Critical Care: guide/pulmonology-critical-care.md
    - Rheumatology: guide/rheumatology.md
  - Other Topics:
    - Basics: other-topics/1-basics.md
    - Dotphrases: other-topics/dotphrases.md
    - Cerner: other-topics/2-cerner.md
    - Shortcuts: other-topics/2-cerner-shortcuts.md
    - FASTHUGSBID: other-topics/3-FASTHUGSBID.md
    - Team Expectations: other-topics/5-team-expectations.md
    - Staying Organized: other-topics/3-staying-organized.md
    - How to Write an Admission Note: other-topics/4-how-to-write-admit-note.md
    - Transfers: other-topics/5-transfers.md
    - Common Inpatient Problems: other-topics/8-common-inpt-problems.md
    - Discharge Summary: other-topics/5-discharge-summary.md
    - Patient Instructions: other-topics/2-patient-instructions.md
  - Resources: 
    - resources/index.md
    - Important Websites: resources/important-websites.md
    - About: resources/about.md
    - Changelog: resources/changelog.md
  - Tags: tags.md
  - Blog:
    - blog/index.md
  - Disclaimer: 
    - disclaimer/index.md
    - License: disclaimer/license.md

validation:
  links:
    absolute_links: ignore

watch:
  - material

exclude_docs:
  draft/