# Project information
site_name: Docsref
site_url: https://www.docsref.com/
site_author: Austin
site_description: >-
  Information, fast

# Repository
repo_name: jzstraley/docsref
repo_url: https://github.com/jzstraley/docsref/

# Copyright
copyright: Copyright &copy; 2022 - 2024 Austin

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo3-copy-invert.png

# Plugins
plugins:
  - blog:
      blog_dir: .
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/stylesheets/extra.css
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: iso_datetime
      timezone: America/Detroit
      fallback_to_build_date: true

strict: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-DRP25XGTN2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jzstraley
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/austinthefamilyguy/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jamesstraley
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Straley/

# Extra CSS
extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: IMTechEd
      repo: IMTechEd
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: 'index.md'
  - IM Guide:
    - Student/Intern Readings: im-guide/student-intern-readings.md
    - Cardiology:
      - im-guide/cardiology/index.md
      - ACS: im-guide/cardiology/acs.md
      - Cardiac Critical Care: im-guide/cardiology/cardiac-critical-care.md
      - Congenital Heart Disease: im-guide/cardiology/congenital-heart-disease.md
      - Consults: im-guide/cardiology/consults.md
      - Echo: 
        - im-guide/cardiology/index.md
      - EKG: im-guide/cardiology/ekg.md
      - Electrophysiology: 
        - im-guide/cardiology/electrophysiology/index.md
        - Atrial Fibrillation: im-guide/cardiology/electrophysiology/atrial-fibrillation.md
      - Heart Failure: 
        - im-guide/cardiology/index.md
        - RV Failure: im-guide/cardiology/heart-failure/rvfailure.md
      - Imaging: im-guide/cardiology/imaging.md
      - Invasive Cardiology: im-guide/cardiology/invasive-cardiology.md
      - Nuclear Cardiology: im-guide/cardiology/nuclear-cardiology.md
      - Other Topics: 
        - im-guide/cardiology/other-topics/index.md
        - Syncope: im-guide/cardiology/other-topics/syncope.md
      - Pericardial Disease: im-guide/cardiology/pericardial-disease.md
      - Pharmacology: im-guide/cardiology/pharmacology-cardiology.md
      - Prevention: 
        - im-guide/cardiology/prevention/index.md
        - Lipids: im-guide/cardiology/prevention/lipids.md
      - Reasarch: im-guide/cardiology/research.md
      - Stable Ischemic Disease: im-guide/cardiology/stable-ischemic-disease.md
      - Vascular Disease: 
        - im-guide/cardiology/vascular-disease/index.md
        - Hypertension: im-guide/cardiology/vascular-disease/hypertension.md
      - Valvular Heart Disease: 
        - im-guide/cardiology/valvular-heart-disease/index.md
    - Dermatology: im-guide/dermatology.md
    - Endocrinology: im-guide/endocrinology.md
    - Gastroenterology: im-guide/gastroenterology.md
    - General: im-guide/general.md
    - Geriatrics: im-guide/geriatrics.md
    - Hematology/Oncology: im-guide/hematology-oncology.md
    - Infectious Disease: im-guide/infectious-disease.md
    - Neurology: im-guide/neurology.md
    - Nephrology: 
      - im-guide/nephrology/index.md
      - Renal Anatomy: im-guide/nephrology/renal-anatomy.md
      - Renal Physiology: im-guide/nephrology/renal-physiology.md
      - Electrolytes: 
        - im-guide/nephrology/electrolytes/index.md
        - Hypernatremia: im-guide/nephrology/electrolytes/hypernatremia.md
        - Hyponatremia: im-guide/nephrology/electrolytes/hyponatremia.md
        - Hypomagnesemia: im-guide/nephrology/electrolytes/hypomagnesemia.md
        - Hyperkalemia: im-guide/nephrology/electrolytes/hyperkalemia.md
        - Hypokalemia: im-guide/nephrology/electrolytes/hypokalemia.md
        - Hypercalcemia: im-guide/nephrology/electrolytes/hypercalcemia.md
        - Hypocalcemia: im-guide/nephrology/electrolytes/hypocalcemia.md
        - Hyperphosphatemia: im-guide/nephrology/electrolytes/hyperphosphatemia.md
        - Hypophosphatemia: im-guide/nephrology/electrolytes/hypophosphatemia.md
        - Hypermagnesemia: im-guide/nephrology/electrolytes/hypermagnesemia.md
      - AKI: im-guide/nephrology/aki.md
      - CKD: im-guide/nephrology/ckd.md
    - Pharmacology: 
      - im-guide/pharmacology/index.md
      - Autonomics: im-guide/pharmacology/autonomics.md
      - Chemotherapy & ID:
        - im-guide/pharmacology/Chemotherapy & ID/index.md
        - Antibiotics: im-guide/pharmacology/Chemotherapy & ID/antibiotics.md
        - Antiemetics: im-guide/pharmacology/Chemotherapy & ID/antiemetics.md
        - Antivirals: im-guide/pharmacology/Chemotherapy & ID/antivirals.md
        - Oncologic Meds: im-guide/pharmacology/Chemotherapy & ID/oncologic_meds.md
      - Endocrine:
        - im-guide/pharmacology/Endocrine/index.md
        - Anti-Obesity: im-guide/pharmacology/Endocrine/antiobesity.md
        - Diabetes Management: im-guide/pharmacology/Endocrine/diabetes_management.md
        - Osteoporosis: im-guide/pharmacology/Endocrine/osteoporosis.md
        - Thyroid Meds: im-guide/pharmacology/Endocrine/thyroid_meds.md
      - Labs and Side Effects:
        - im-guide/pharmacology/Labs and Side Effects/index.md
        - General: im-guide/pharmacology/Labs and Side Effects/general.md
        - Labs: im-guide/pharmacology/Labs and Side Effects/labs.md
        - Other: im-guide/pharmacology/Labs and Side Effects/other.md
        - Side Effects: im-guide/pharmacology/Labs and Side Effects/side_effects.md
      - Nervous System:
        - im-guide/pharmacology/Nervous System/index.md
        - Anesthetics: im-guide/pharmacology/Nervous System/anesthetics.md
        - Anticonvulsants: im-guide/pharmacology/Nervous System/anticonvulsants.md
        - CNS Drugs: im-guide/pharmacology/Nervous System/cnsdrugs.md
        - ICU: im-guide/pharmacology/Nervous System/icu.md
        - Pain Management: im-guide/pharmacology/Nervous System/pain_management.md
        - Sleep: im-guide/pharmacology/Nervous System/sleep.md
      - Psychiatry:
        - im-guide/pharmacology/Psychiatry/index.md
        - Antidepressants: im-guide/pharmacology/Psychiatry/antidepressants.md
        - Antipsychotics: im-guide/pharmacology/Psychiatry/antipsychotics.md
        - Anxiolytics: im-guide/pharmacology/Psychiatry/anxiolytics.md
        - Mood Stabilizers: im-guide/pharmacology/Psychiatry/mood_stabilizers.md
        - Stimulants: im-guide/pharmacology/Psychiatry/stimulants.md
      - Smooth Muscle:
        - im-guide/pharmacology/Smooth Muscle/index.md
        - Anaphylaxis: im-guide/pharmacology/Smooth Muscle/anaphylaxis.md
        - Antihistamines: im-guide/pharmacology/Smooth Muscle/antihistamines.md
        - Antipruritics: im-guide/pharmacology/Smooth Muscle/antipruritics.md
        - Asthma/COPD: im-guide/pharmacology/Smooth Muscle/asthma-copd.md
        - Decongestants: im-guide/pharmacology/Smooth Muscle/decongestants.md
      - Special Topics:
        - im-guide/pharmacology/Special Topics/index.md
        - Antidiarrheals: im-guide/pharmacology/Special Topics/antidiarrheals.md
        - Contraceptives: im-guide/pharmacology/Special Topics/contraceptives.md
        - Dermatology: im-guide/pharmacology/Special Topics/dermatology.md
        - GERD: im-guide/pharmacology/Special Topics/gerd.md
        - Laxatives: im-guide/pharmacology/Special Topics/laxatives.md
        - Pregnancy: im-guide/pharmacology/Special Topics/pregnancy.md
        - Prostate: im-guide/pharmacology/Special Topics/prostate.md
        - Vitamins: im-guide/pharmacology/Special Topics/vitamins.md
      - Toxicology: im-guide/pharmacology/Toxicology/index.md
      - Blood & Anti-inflammatories:
        - im-guide/pharmacology/blood&anti-inflammatories/index.md
        - Antiplatelets: im-guide/pharmacology/blood&anti-inflammatories/antiplatelets.md
        - Antithrombotics: im-guide/pharmacology/blood&anti-inflammatories/antithrombotics.md
        - Fibrinolytics: im-guide/pharmacology/blood&anti-inflammatories/fibrinolytics.md
        - Gout: im-guide/pharmacology/blood&anti-inflammatories/gout.md
        - Steroids: im-guide/pharmacology/blood&anti-inflammatories/steroids.md
      - Cardiovascular Renal:
        - im-guide/pharmacology/cardiovascular-renal/index.md
        - Antianginals: im-guide/pharmacology/cardiovascular-renal/antianginals.md
        - Antiarrhythmics: im-guide/pharmacology/cardiovascular-renal/antiarrhythmics.md
        - Antihypertensives: im-guide/pharmacology/cardiovascular-renal/antihypertensives.md
        - Lipid Therapy: im-guide/pharmacology/cardiovascular-renal/lipidtherapy.md
    - Pulmonology/Critical Care: 
        - im-guide/index.md
        - FASTHUGSBID: im-guide/pccm/fasthugsbid.md
    - Rheumatology: im-guide/rheumatology.md
  - Resident Guide:
    - Basics: resident-guide/1-basics.md
    - Team Expectations: resident-guide/2-team-expectations.md
    - Staying Organized: resident-guide/3-staying-organized.md
    - How to Write an Admission Note: resident-guide/4-how-to-write-admit-note.md
    - Transfers: resident-guide/5-transfers.md
    - Discharge Summary: resident-guide/6-discharge-summary.md
    - Patient Instructions: resident-guide/7-patient-instructions.md
    - Common Inpatient Problems: resident-guide/8-common-inpt-problems.md
  - Resources:
    - Cerner: resources/cernerhelp.md
    - Dotphrases: resources/dotphrases.md
    - Important Websites: resources/important-websites.md
    - Shortcuts: resources/shortcuts.md
    - Blog: 
      - resources/blog/index.md
  - Tags: tags.md
  - Disclaimer: 
    - disclaimer/index.md
    - License: disclaimer/license.md
    - Changelog: disclaimer/changelog.md
  - About: about.md

validation:
  links:
    absolute_links: ignore

watch:
  - material

exclude_docs:
  draft/